title: Keeping it real with Kgothatso
author: Kgothatso Langa
email: klanga07@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a third year Geoinformatics student at the University of Pretoria.

theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

